### ISSUE TITLE
[Joss Review] Community guidelines

### ISSUE THREAD

**Issue by mbeyss** [xianggebenben/GraphSL#15]
related to this [JOSS Review](https://github.com/openjournals/joss-reviews/issues/6796)

Please expand the `Contact` section of the README fot include

guidelines for third parties wishing to 
1. Contribute to the software
2. Report issues or problems with the software
3. Seek support

3rd one seems covered and the other two are no brainers (pull request and issues in this repo). Just state it explicitly please.

**Comment by xianggebenben** [comment]
Thank you for the suggestion. We have updated the contact section, which is shown as follows:

# Contact
We welcome your contributions! If you’d like to contribute your datasets or algorithms, please submit a pull request consisting of an atomic commit and a brief message describing your contribution.

For a new dataset, please upload it to the [data](https://github.com/xianggebenben/GraphSL/tree/main/data) folder. The file should be a dictionary object saved by [pickle](https://docs.python.org/3/library/pickle.html). It contains a key "adj_mat" with the value of a graph adjacency matrix (sprase numpy array with the [CSR](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html) format).

For a new algorithm, please determine whether it belongs to prescribed methods or GNN-based methods: if it belongs to the prescribed methods,  add your algorithm as a new class in the [GraphSL/Prescribed.py](https://github.com/xianggebenben/GraphSL/blob/main/GraphSL/Prescribed.py). Otherwise, please upload it as a folder under the [GraphSL/GNN](https://github.com/xianggebenben/GraphSL/tree/main/GraphSL/GNN) folder. Typically, the algorithm should include a "train" function and a "test" function, and the "test" function should return a [Metric](https://github.com/xianggebenben/GraphSL/blob/main/GraphSL/Evaluation.py) object.

Feel free to Email me (junxiang.wang@alumni.emory.edu) if you have any questions. Bug reports and feedback can be directed to the [Github issues page](https://github.com/xianggebenben/GraphSL/issues).
